//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigesoft.Node.WinClient.UI.NatclarXML {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XmlDatosPaciente", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class XmlDatosPaciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DepartamentoNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DistritoNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ProvinciaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidenciaActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DepartamentoNacimiento {
            get {
                return this.DepartamentoNacimientoField;
            }
            set {
                if ((this.DepartamentoNacimientoField.Equals(value) != true)) {
                    this.DepartamentoNacimientoField = value;
                    this.RaisePropertyChanged("DepartamentoNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DistritoNacimiento {
            get {
                return this.DistritoNacimientoField;
            }
            set {
                if ((this.DistritoNacimientoField.Equals(value) != true)) {
                    this.DistritoNacimientoField = value;
                    this.RaisePropertyChanged("DistritoNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCivilField, value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaNacimientoField, value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HC {
            get {
                return this.HCField;
            }
            set {
                if ((object.ReferenceEquals(this.HCField, value) != true)) {
                    this.HCField = value;
                    this.RaisePropertyChanged("HC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ProvinciaNacimiento {
            get {
                return this.ProvinciaNacimientoField;
            }
            set {
                if ((this.ProvinciaNacimientoField.Equals(value) != true)) {
                    this.ProvinciaNacimientoField = value;
                    this.RaisePropertyChanged("ProvinciaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidenciaActual {
            get {
                return this.ResidenciaActualField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenciaActualField, value) != true)) {
                    this.ResidenciaActualField = value;
                    this.RaisePropertyChanged("ResidenciaActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoXMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorXML {
            get {
                return this.ErrorXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorXMLField, value) != true)) {
                    this.ErrorXMLField = value;
                    this.RaisePropertyChanged("ErrorXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoXML {
            get {
                return this.EstadoXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoXMLField, value) != true)) {
                    this.EstadoXMLField = value;
                    this.RaisePropertyChanged("EstadoXML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XmlDatosExamen", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class XmlDatosExamen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDActuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCentroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDEstructuraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDExamenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoExamenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRegistroField, value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDActuacion {
            get {
                return this.IDActuacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IDActuacionField, value) != true)) {
                    this.IDActuacionField = value;
                    this.RaisePropertyChanged("IDActuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCentro {
            get {
                return this.IDCentroField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCentroField, value) != true)) {
                    this.IDCentroField = value;
                    this.RaisePropertyChanged("IDCentro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDEstado {
            get {
                return this.IDEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IDEstadoField, value) != true)) {
                    this.IDEstadoField = value;
                    this.RaisePropertyChanged("IDEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDEstructura {
            get {
                return this.IDEstructuraField;
            }
            set {
                if ((object.ReferenceEquals(this.IDEstructuraField, value) != true)) {
                    this.IDEstructuraField = value;
                    this.RaisePropertyChanged("IDEstructura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDExamen {
            get {
                return this.IDExamenField;
            }
            set {
                if ((object.ReferenceEquals(this.IDExamenField, value) != true)) {
                    this.IDExamenField = value;
                    this.RaisePropertyChanged("IDExamen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoExamen {
            get {
                return this.TipoExamenField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoExamenField, value) != true)) {
                    this.TipoExamenField = value;
                    this.RaisePropertyChanged("TipoExamen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstructuraDatosAlergias", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class EstructuraDatosAlergias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosAlergias AlergiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosExamen DatosExamenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosPaciente DatosPacienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosAlergias Alergias {
            get {
                return this.AlergiasField;
            }
            set {
                if ((object.ReferenceEquals(this.AlergiasField, value) != true)) {
                    this.AlergiasField = value;
                    this.RaisePropertyChanged("Alergias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosExamen DatosExamen {
            get {
                return this.DatosExamenField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosExamenField, value) != true)) {
                    this.DatosExamenField = value;
                    this.RaisePropertyChanged("DatosExamen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosPaciente DatosPaciente {
            get {
                return this.DatosPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosPacienteField, value) != true)) {
                    this.DatosPacienteField = value;
                    this.RaisePropertyChanged("DatosPaciente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XmlDatosAlergias", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class XmlDatosAlergias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioField, value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstructuraDatosAPMedicos", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class EstructuraDatosAPMedicos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlAntecedentesPatologicosMedicos APMEDICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosExamen DatosExamenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosPaciente DatosPacienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlAntecedentesPatologicosMedicos APMEDICOS {
            get {
                return this.APMEDICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.APMEDICOSField, value) != true)) {
                    this.APMEDICOSField = value;
                    this.RaisePropertyChanged("APMEDICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosExamen DatosExamen {
            get {
                return this.DatosExamenField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosExamenField, value) != true)) {
                    this.DatosExamenField = value;
                    this.RaisePropertyChanged("DatosExamen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosPaciente DatosPaciente {
            get {
                return this.DatosPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosPacienteField, value) != true)) {
                    this.DatosPacienteField = value;
                    this.RaisePropertyChanged("DatosPaciente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XmlAntecedentesPatologicosMedicos", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class XmlAntecedentesPatologicosMedicos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntecedenteLaboralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AntecedenteLaboral {
            get {
                return this.AntecedenteLaboralField;
            }
            set {
                if ((object.ReferenceEquals(this.AntecedenteLaboralField, value) != true)) {
                    this.AntecedenteLaboralField = value;
                    this.RaisePropertyChanged("AntecedenteLaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCIE {
            get {
                return this.CodigoCIEField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCIEField, value) != true)) {
                    this.CodigoCIEField = value;
                    this.RaisePropertyChanged("CodigoCIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFinField, value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioField, value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstructuraDatosAPQuirurgicos", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class EstructuraDatosAPQuirurgicos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlAntecedentesPatologicosQuirurgicos APQUIRURGICOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosExamen DatosExamenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosPaciente DatosPacienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlAntecedentesPatologicosQuirurgicos APQUIRURGICOS {
            get {
                return this.APQUIRURGICOSField;
            }
            set {
                if ((object.ReferenceEquals(this.APQUIRURGICOSField, value) != true)) {
                    this.APQUIRURGICOSField = value;
                    this.RaisePropertyChanged("APQUIRURGICOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosExamen DatosExamen {
            get {
                return this.DatosExamenField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosExamenField, value) != true)) {
                    this.DatosExamenField = value;
                    this.RaisePropertyChanged("DatosExamen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosPaciente DatosPaciente {
            get {
                return this.DatosPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosPacienteField, value) != true)) {
                    this.DatosPacienteField = value;
                    this.RaisePropertyChanged("DatosPaciente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XmlAntecedentesPatologicosQuirurgicos", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProveedorExterno")]
    [System.SerializableAttribute()]
    public partial class XmlAntecedentesPatologicosQuirurgicos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntecedenteLaboralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AntecedenteLaboral {
            get {
                return this.AntecedenteLaboralField;
            }
            set {
                if ((object.ReferenceEquals(this.AntecedenteLaboralField, value) != true)) {
                    this.AntecedenteLaboralField = value;
                    this.RaisePropertyChanged("AntecedenteLaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCIE {
            get {
                return this.CodigoCIEField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCIEField, value) != true)) {
                    this.CodigoCIEField = value;
                    this.RaisePropertyChanged("CodigoCIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFinField, value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioField, value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NatclarXML.IWSRIProveedorExterno")]
    public interface IWSRIProveedorExterno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosPaciente", ReplyAction="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosPacienteResponse")]
        Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosPaciente(Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosPaciente XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosExamen", ReplyAction="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosExamenResponse")]
        Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosExamen(Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosExamen XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosAlergias", ReplyAction="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosAlergiasResponse")]
        Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosAlergias(Sigesoft.Node.WinClient.UI.NatclarXML.EstructuraDatosAlergias XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosAPMedicos", ReplyAction="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosAPMedicosResponse")]
        Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosAPMedicos(Sigesoft.Node.WinClient.UI.NatclarXML.EstructuraDatosAPMedicos XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosAPQuirurgicos", ReplyAction="http://tempuri.org/IWSRIProveedorExterno/EnviarDatosAPQuirurgicosResponse")]
        Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosAPQuirurgicos(Sigesoft.Node.WinClient.UI.NatclarXML.EstructuraDatosAPQuirurgicos XML);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSRIProveedorExternoChannel : Sigesoft.Node.WinClient.UI.NatclarXML.IWSRIProveedorExterno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSRIProveedorExternoClient : System.ServiceModel.ClientBase<Sigesoft.Node.WinClient.UI.NatclarXML.IWSRIProveedorExterno>, Sigesoft.Node.WinClient.UI.NatclarXML.IWSRIProveedorExterno {
        
        public WSRIProveedorExternoClient() {
        }
        
        public WSRIProveedorExternoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSRIProveedorExternoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRIProveedorExternoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRIProveedorExternoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosPaciente(Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosPaciente XML) {
            return base.Channel.EnviarDatosPaciente(XML);
        }
        
        public Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosExamen(Sigesoft.Node.WinClient.UI.NatclarXML.XmlDatosExamen XML) {
            return base.Channel.EnviarDatosExamen(XML);
        }
        
        public Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosAlergias(Sigesoft.Node.WinClient.UI.NatclarXML.EstructuraDatosAlergias XML) {
            return base.Channel.EnviarDatosAlergias(XML);
        }
        
        public Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosAPMedicos(Sigesoft.Node.WinClient.UI.NatclarXML.EstructuraDatosAPMedicos XML) {
            return base.Channel.EnviarDatosAPMedicos(XML);
        }
        
        public Sigesoft.Node.WinClient.UI.NatclarXML.Resultado EnviarDatosAPQuirurgicos(Sigesoft.Node.WinClient.UI.NatclarXML.EstructuraDatosAPQuirurgicos XML) {
            return base.Channel.EnviarDatosAPQuirurgicos(XML);
        }
    }
}
