//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/04/03 - 00:50:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="systemuserrolenode"/> and <see cref="systemuserrolenodeDto"/>.
    /// </summary>
    public static partial class systemuserrolenodeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="systemuserrolenodeDto"/> converted from <see cref="systemuserrolenode"/>.</param>
        static partial void OnDTO(this systemuserrolenode entity, systemuserrolenodeDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="systemuserrolenode"/> converted from <see cref="systemuserrolenodeDto"/>.</param>
        static partial void OnEntity(this systemuserrolenodeDto dto, systemuserrolenode entity);

        /// <summary>
        /// Converts this instance of <see cref="systemuserrolenodeDto"/> to an instance of <see cref="systemuserrolenode"/>.
        /// </summary>
        /// <param name="dto"><see cref="systemuserrolenodeDto"/> to convert.</param>
        public static systemuserrolenode ToEntity(this systemuserrolenodeDto dto)
        {
            if (dto == null) return null;

            var entity = new systemuserrolenode();

            entity.i_SystemUserId = dto.i_SystemUserId;
            entity.i_NodeId = dto.i_NodeId;
            entity.i_RoleId = dto.i_RoleId;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.i_InsertUserId = dto.i_InsertUserId;
            entity.d_InsertDate = dto.d_InsertDate;
            entity.i_UpdateUserId = dto.i_UpdateUserId;
            entity.d_UpdateDate = dto.d_UpdateDate;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="systemuserrolenode"/> to an instance of <see cref="systemuserrolenodeDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="systemuserrolenode"/> to convert.</param>
        public static systemuserrolenodeDto ToDTO(this systemuserrolenode entity)
        {
            if (entity == null) return null;

            var dto = new systemuserrolenodeDto();

            dto.i_SystemUserId = entity.i_SystemUserId;
            dto.i_NodeId = entity.i_NodeId;
            dto.i_RoleId = entity.i_RoleId;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.i_InsertUserId = entity.i_InsertUserId;
            dto.d_InsertDate = entity.d_InsertDate;
            dto.i_UpdateUserId = entity.i_UpdateUserId;
            dto.d_UpdateDate = entity.d_UpdateDate;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="systemuserrolenodeDto"/> to an instance of <see cref="systemuserrolenode"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<systemuserrolenode> ToEntities(this IEnumerable<systemuserrolenodeDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="systemuserrolenode"/> to an instance of <see cref="systemuserrolenodeDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<systemuserrolenodeDto> ToDTOs(this IEnumerable<systemuserrolenode> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
